# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "tussi law blog" 
tagline:          'law in a nutshell'
description:      'understanding law for everybody'
url:              https://tussihack.github.io/blog/
baseurl:          https://tussihack.github.io/blog/

author:
  name:          'tussihack'
  url:           https://twitter.com/TussiLaw

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

theme: jekyll-theme-cayman
